//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIMERTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MIMERTests.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///MIME-Version: 1.0
        ///Date: Thu, 02 Sep 2004 15:38:17 -0500
        ///Message-ID: &lt;CHILKAT-MID-aea4b5d4-7786-4124-8c78-6e6d743e63c3@DotNetDev&gt;
        ///X-Mailer: Chilkat Software Inc (http://www.chilkatsoft.com)
        ///X-Priority: 3 (Normal)
        ///Content-Type: text/plain; charset=&quot;gb2312&quot;
        ///Content-Transfer-Encoding: base64
        ///subject: =?gb2312?B?z+MguNsghIIgvVkgyvgg6Uwg?=
        ///			=?gb2312?B?318gzuUgxOogtuA=?=
        ///To: =?gb2312?B?zuUgxOogtuA=?= &lt;support@chilkatsoft.com&gt;
        ///From: =?gb2312?B?zuUgxOogtuA=?= &lt;programmer@chilkatsoft.com&gt;
        ///return-path:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Big5MailMEssage {
            get {
                return ResourceManager.GetString("Big5MailMEssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type: image/jpeg
        ///Content-Disposition: attachment; filename=genome.jpeg;
        ///          modification-date=&quot;Wed, 12 Feb 1997 16:29:51 -0500&quot;;
        ///Content-Description: a complete map of the human genome.
        /// </summary>
        internal static string ContentDispositionFields {
            get {
                return ResourceManager.GetString("ContentDispositionFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content-Type: multipart/alternative; boundary=&quot;_----------=_1161875317892621109&quot;
        ///Content-Type: text/plain; charset=&quot;iso-8859-1&quot;
        ///Content-Type: text/html; charset=&quot;iso-8859-1&quot;.
        /// </summary>
        internal static string ContentTypeFields {
            get {
                return ResourceManager.GetString("ContentTypeFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: =?iso-8859-1?Q?Robert_Wallstr=F6m?= &lt;mrx@unknown.com&gt;.
        /// </summary>
        internal static string ExtendedField {
            get {
                return ResourceManager.GetString("ExtendedField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received: by cuba.smithimage.com 
        ///	id &lt;01C6F16A.9E23D61D@cuba.smithimage.com&gt;; Mon, 16 Oct 2006 23:32:44 +0200
        ///Content-class: urn:content-classes:message
        ///Subject: =?iso-8859-1?Q?Funkar_detta_d=E5?=
        ///Date: Mon, 16 Oct 2006 23:32:46 +0200
        ///Message-ID: &lt;13176CE1A8A2C4428E514E5E603A56C067BC@cuba.smithimage.com&gt;
        ///MIME-Version: 1.0
        ///Content-Type: multipart/alternative;
        ///	boundary=&quot;----_=_NextPart_001_01C6F16A.9E23D61D&quot;
        ///X-MS-Has-Attach: 
        ///X-MS-TNEF-Correlator: 
        ///Thread-Topic: =?iso-8859-1?Q?Funkar_detta_d=E5?= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtendedFields {
            get {
                return ResourceManager.GetString("ExtendedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-Path: &lt;smithimage=home.se@pluto.fl-net.se&gt;
        ///Received: from cmdeliver.vip.spray.net (lmin05.st1.spray.net [212.78.202.105])	by cmdeliver03.st1.spray.net (Postfix) with ESMTP id 6448AFA5C0C	for &lt;smithimage_home.se@spray.se&gt;; Thu, 26 Oct 2006 15:45:12 +0000 (GMT)
        ///Received: from pluto.fl-net.se (pluto.fl-net.se [62.13.76.12])	by lmin05.st1.spray.net (Postfix) with SMTP id 0192233F68	for &lt;smithimage@home.se&gt;; Thu, 26 Oct 2006 15:45:08 +0000 (GMT)
        ///Received: (qmail 11539 invoked by uid 500); 26 Oct 2006 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-Path: &lt;smithimage=home.se@pluto.fl-net.se&gt;
        ///Received: from cmdeliver.vip.spray.net (lmin05.st1.spray.net [212.78.202.105])	by cmdeliver03.st1.spray.net (Postfix) with ESMTP id 6448AFA5C0C	for &lt;smithimage_home.se@spray.se&gt;; Thu, 26 Oct 2006 15:45:12 +0000 (GMT)
        ///Received: from pluto.fl-net.se (pluto.fl-net.se [62.13.76.12])	by lmin05.st1.spray.net (Postfix) with SMTP id 0192233F68	for &lt;smithimage@home.se&gt;; Thu, 26 Oct 2006 15:45:08 +0000 (GMT)
        ///Received: (qmail 11539 invoked by uid 500); 26 Oct 2006 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailMessage1 {
            get {
                return ResourceManager.GetString("MailMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered-To: smithimage@gmail.com
        ///Received: by 10.140.207.17 with SMTP id e17cs87083rvg;
        ///        Fri, 25 Apr 2008 01:24:39 -0700 (PDT)
        ///Received: by 10.86.3.4 with SMTP id 4mr629916fgc.3.1209111438969;
        ///        Fri, 25 Apr 2008 01:17:18 -0700 (PDT)
        ///Return-Path: &lt;noreply@javaforum.se&gt;
        ///Received: from javaforum.se (javaforum.se [192.176.10.128])
        ///        by mx.google.com with ESMTP id e8si6206188muf.8.2008.04.25.01.17.16;
        ///        Fri, 25 Apr 2008 01:17:18 -0700 (PDT)
        ///Received-SPF: pass (google.com: best [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailMessage2 {
            get {
                return ResourceManager.GetString("MailMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return-Path: &lt;mrx@unknown.com&gt;
        ///Received: from cmdeliver.vip.spray.net (unknown [212.78.203.177])
        ///	by cmdeliver05.st1.spray.net (Postfix) with ESMTP id 8EEC98BF48
        ///	for &lt;smithimage_home.se@spray.se&gt;; Mon,  4 Jun 2007 20:59:11 +0000 (GMT)
        ///Received: from mxfep01.bredband.com (localhost.localdomain [127.0.0.1])
        ///	by lmin18.st1.spray.net (Postfix) with SMTP id 1825F3CEDB7
        ///	for &lt;smithimage@home.se&gt;; Mon,  4 Jun 2007 22:58:54 +0200 (CEST)
        ///Received: from 195.54.107.70/32:46499 (from=&lt;mrx@unknown.com&gt;;helo=mxfe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailMessageWithAttachment {
            get {
                return ResourceManager.GetString("MailMessageWithAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received: by cuba.smithimage.com 
        ///	id &lt;01C7EBEA.CBD303A2@cuba.smithimage.com&gt;; Fri, 31 Aug 2007 18:20:07 +0200
        ///Content-class: urn:content-classes:message
        ///Subject: test med embeded och bilagor i det embeddade
        ///Date: Fri, 31 Aug 2007 18:20:05 +0200
        ///MIME-Version: 1.0
        ///Content-Type: multipart/mixed;
        ///	boundary=&quot;----_=_NextPart_001_01C7EBEA.CBD303A2&quot;
        ///Message-ID: &lt;13176CE1A8A2C4428E514E5E603A56C06809@cuba.smithimage.com&gt;
        ///X-MS-Has-Attach: yes
        ///X-MS-TNEF-Correlator: 
        ///Thread-Topic: test med embeded och bilago [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailMessageWithEmbeddedWithAttachments {
            get {
                return ResourceManager.GetString("MailMessageWithEmbeddedWithAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received: by cuba.smithimage.com 
        ///	id &lt;01C7E5C1.273AADE9@cuba.smithimage.com&gt;; Thu, 23 Aug 2007 22:06:55 +0200
        ///Content-class: urn:content-classes:message
        ///Subject: Test med flera olika
        ///Date: Thu, 23 Aug 2007 22:06:54 +0200
        ///MIME-Version: 1.0
        ///Message-ID: &lt;13176CE1A8A2C4428E514E5E603A56C06807@cuba.smithimage.com&gt;
        ///Content-Type: multipart/mixed;
        ///	boundary=&quot;----_=_NextPart_001_01C7E5C1.273AADE9&quot;
        ///X-MS-Has-Attach: yes
        ///X-MS-TNEF-Correlator: 
        ///Thread-Topic: Test med flera olika
        ///x-mimeole: Produced By Micros [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MailMessageWithRecursivlyEmbeddedMessage {
            get {
                return ResourceManager.GetString("MailMessageWithRecursivlyEmbeddedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIME-Version: 1.0
        ///Date: Tue, 12 May 2009 02:15:15 +0000
        ///To: fax.alcatel.ca@carlsonwagonlit.com
        ///CC: 
        ///From: &quot;eFax Corporate&quot; &lt;message@inbound.efax.com&gt;
        ///Subject: =?utf-8?Q?
        ///Corporate=20eFax=20message=20from=20&quot;416=20798=200125&quot;=20-=201=20page(s)?=
        ///Message_Id: &lt;toronto1_did1-1242094487-4169817263-14-
        ///5310.1242094515@medora2.toronto1&gt;
        ///Content-Type: Multipart/Mixed;boundary=&quot;Boundary-00=_T7P340MWKGMMYJ0CCJD0&quot;
        ///X-OriginalArrivalTime: 12 May 2009 02:17:06.0872 (UTC) FILETIME=
        ///[BF5D8B80:01C9D2A7]
        ///X-Virus- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NonStandardBoundary {
            get {
                return ResourceManager.GetString("NonStandardBoundary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ä-läläöläö.äö.äööääöläää.ä.ä
        ///älöäsdfä.
        ///.äsldäflsäää.
        /// </summary>
        internal static string QuotedPrintableDecoded {
            get {
                return ResourceManager.GetString("QuotedPrintableDecoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =E4-l=E4l=E4=F6l=E4=F6.=E4=F6.=E4=F6=F6=E4=E4=F6l=E4=E4=E4.=E4.=E4
        ///=E4l=F6=E4sdf=E4.
        ///.=E4sld=E4fls=E4=E4=E4.
        /// </summary>
        internal static string QuotedPrintableEncoded {
            get {
                return ResourceManager.GetString("QuotedPrintableEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered-To: smithimage@gmail.com
        ///Received: by 10.114.120.13 with SMTP id s13cs597787wac;
        ///        Sun, 15 Jun 2008 13:35:28 -0700 (PDT)
        ///Received: by 10.210.58.13 with SMTP id g13mr5407172eba.54.1213562126621;
        ///        Sun, 15 Jun 2008 13:35:26 -0700 (PDT)
        ///Return-Path: &lt;mrx@unknown.com&gt;
        ///Received: from proxy3.bredband.net (proxy3.bredband.net [195.54.101.73])
        ///        by mx.google.com with ESMTP id c25si7403713ika.11.2008.06.15.13.35.25;
        ///        Sun, 15 Jun 2008 13:35:26 -0700 (PDT)
        ///Received-SPF: pass [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SMIME_CERT {
            get {
                return ResourceManager.GetString("SMIME_CERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered-To: smithimage@gmail.com
        ///Received: by 10.140.147.7 with SMTP id u7cs32233rvd;
        ///        Tue, 1 Jul 2008 11:28:21 -0700 (PDT)
        ///Received: by 10.67.10.8 with SMTP id n8mr533264ugi.23.1214936790541;
        ///        Tue, 01 Jul 2008 11:26:30 -0700 (PDT)
        ///Return-Path: &lt;mrx@unknown.com&gt;
        ///Received: from proxy1.bredband.net (proxy1.bredband.net [195.54.101.71])
        ///        by mx.google.com with ESMTP id p32si1555372ugc.44.2008.07.01.11.26.00;
        ///        Tue, 01 Jul 2008 11:26:30 -0700 (PDT)
        ///Received-SPF: pass (google [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SMIME_MESSAGE {
            get {
                return ResourceManager.GetString("SMIME_MESSAGE", resourceCulture);
            }
        }
    }
}
